<a href="https://colab.research.google.com/github/aliang9/nlpfa23/blob/main/cosine_sim.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!pip install pandas gensim scikit-learn
!pip install -U sentence-transformers
import pandas as pd
from gensim.models import Word2Vec
from sklearn.metrics.pairwise import cosine_similarity
from sentence_transformers import SentenceTransformer
import numpy as np

In [ ]:
model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')

csv_path = '/content/drive/MyDrive/NLPProject/reddit-explanations-wgpt_filled.csv'
df = pd.read_csv(csv_path)


# Function to calculate cosine similarity between two strings given embeddings
def calculate_similarity(vec1, vec2):
    if np.linalg.norm(vec1) == 0 or np.linalg.norm(vec2) == 0:
        return 0.0  # Handle the case where a vector has zero norm
    return cosine_similarity([vec1], [vec2])[0][0]

column_pairs = [(2,3),
                (2,4),
                (2,5),
                (2,6),
                (2,7),
                (2,8)]

similarity_matrix = []

i = 0
for row in df.itertuples(index=False):
    if i < 6:
        i += 1
        continue
    similarities = [calculate_similarity(model.encode(row[col1]), model.encode(row[col2])) for col1, col2 in column_pairs]
    similarity_matrix.append(similarities)


import numpy as np
similarity_matrix = np.array(similarity_matrix)

print(similarity_matrix)


[[0.80724883 0.8322246  0.7830578  0.754637   0.80973256 0.8188273 ]
 [0.83966947 0.840336   0.86987257 0.82782674 0.7874603  0.82340413]
 [0.5946944  0.48297173 0.61777866 0.85041153 0.6058841  0.7446868 ]
 [0.56991506 0.5294707  0.5174673  0.4681378  0.5059091  0.51726353]
 [0.6189784  0.6436234  0.6169263  0.61295295 0.64043427 0.6221435 ]
 [0.5749427  0.62489116 0.672423   0.67880607 0.6323357  0.61869204]
 [0.76813734 0.8357209  0.7556354  0.8557608  0.8568349  0.8494768 ]
 [0.5381163  0.5498725  0.5180421  0.5816444  0.44681412 0.5372787 ]
 [0.8664925  0.84553987 0.88048923 0.86400306 0.878277   0.8090152 ]
 [0.7038224  0.6253377  0.6253377  0.7518734  0.820629   0.77044517]
 [0.8072013  0.8013966  0.7667217  0.8508644  0.7605685  0.7777555 ]
 [0.6720407  0.7428459  0.6978136  0.72779536 0.69513357 0.76749635]
 [0.78133106 0.8190224  0.8338139  0.8079524  0.7847038  0.83915657]
 [0.7012254  0.6315517  0.7337506  0.69584644 0.6945012  0.7249577 ]
 [0.59326875 0.8160447  0.79183275

In [ ]:
average_values = np.mean(similarity_matrix, axis=0)
print(average_values)

[0.71634686 0.7158705  0.71885455 0.75157017 0.7409605  0.75434947]


##Chinese

In [ ]:
model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')

csv_path = '/content/drive/MyDrive/NLPProject/chinese_explanations_wgpt_filled.csv'
df = pd.read_csv(csv_path)


# Function to calculate cosine similarity between two strings given embeddings
def calculate_similarity(vec1, vec2):
    if np.linalg.norm(vec1) == 0 or np.linalg.norm(vec2) == 0:
        return 0.0  # Handle the case where a vector has zero norm
    return cosine_similarity([vec1], [vec2])[0][0]

column_pairs = [(2,3),
                (2,4),
                (2,5),
                (2,6),
                (2,7),
                (2,8)]

similarity_matrix = []

i = 0
for row in df.itertuples(index=False):
    print(row)
    if i < 6:
        i += 1
        continue
    similarities = [calculate_similarity(model.encode(row[col1]), model.encode(row[col2])) for col1, col2 in column_pairs]
    similarity_matrix.append(similarities)


import numpy as np
similarity_matrix = np.array(similarity_matrix)

print(similarity_matrix)


Pandas(Setups='一天，一位法官的女友看見兩個蚊子，便叫法官打死。\n只見法官只把那個肚子飽飽的蚊子打死了，卻對那隻肚子乾癟的蚊子遲遲不下手。\n女友問他為什麼不把那隻蚊子也打死？', Punchlines='他回答說：證據不足。', Explanation="This is funny because it unexpectedly applies the judge's serious reasoning to a trivial situation. Since the mosquito without a full stomach does not have evidence of drinking a lot of blood, the judge does not kill it.", _3=nan, _4=nan, _5=nan, _6=nan, _7=nan, _8=nan)
Pandas(Setups='辦公室中兩位女同事吵起來了。\n經理忍無可忍：「太不像話了！現在是什麼情況？你們把原因給我說清楚！」\n兩人一聽，又爭先恐後各執一詞吵成一團。\n經理大吼一聲：「夠了！胖的先講！」', Punchlines='頓時，世界安靜了。', Explanation='This is funny because it is unexpected. To get the colleagues to stop arguing, the manager is able to quiet them by asking the fatter person to talk first.', _3=nan, _4=nan, _5=nan, _6=nan, _7=nan, _8=nan)
Pandas(Setups='一位求職者在「專長」一欄中填上「造謠」。\n面試官不信任地說：「你造一次謠給我們看看。」', Punchlines='求職者走到門外，對其他等待面試的人說：「你們可以回去了，我已經得到了這份工作，沒你們的事了。」', Explanation='This is funny because it is ironic. To prove they are able to write rumors to secure the job, the job se

In [ ]:
import numpy as np
average_values = np.mean(similarity_matrix, axis=0)
print(average_values)

[0.6791881  0.6592716  0.628947   0.69131887 0.7126256  0.6803474 ]
